// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxH78ozO1UF7pf8JH1OW_sL-GiRn98dek',
    appId: '1:637749959955:web:e6eb4cc28ad35b5125cee6',
    messagingSenderId: '637749959955',
    projectId: 'lumina-20645',
    authDomain: 'lumina-20645.firebaseapp.com',
    storageBucket: 'lumina-20645.firebasestorage.app',
    measurementId: 'G-HJ86RKF1RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHQuhhTN60Gm-s-u_M89DVpZc_mageWLY',
    appId: '1:637749959955:android:e936a92da4eb4d1d25cee6',
    messagingSenderId: '637749959955',
    projectId: 'lumina-20645',
    storageBucket: 'lumina-20645.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvaDbOez7axFqho7-8hVXscFohLjp4tpo',
    appId: '1:637749959955:ios:5d457a30c3fe941b25cee6',
    messagingSenderId: '637749959955',
    projectId: 'lumina-20645',
    storageBucket: 'lumina-20645.firebasestorage.app',
    iosBundleId: 'com.example.lumina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvaDbOez7axFqho7-8hVXscFohLjp4tpo',
    appId: '1:637749959955:ios:5d457a30c3fe941b25cee6',
    messagingSenderId: '637749959955',
    projectId: 'lumina-20645',
    storageBucket: 'lumina-20645.firebasestorage.app',
    iosBundleId: 'com.example.lumina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxH78ozO1UF7pf8JH1OW_sL-GiRn98dek',
    appId: '1:637749959955:web:2cb7dcec831c193125cee6',
    messagingSenderId: '637749959955',
    projectId: 'lumina-20645',
    authDomain: 'lumina-20645.firebaseapp.com',
    storageBucket: 'lumina-20645.firebasestorage.app',
    measurementId: 'G-4LNSEVTX91',
  );

}